// AVR Multi Motor Control
/*! \file include/common/dcmotor.h
 * DC Motor common definitions
 *
 * \author Paolo Lucchesi
 */
#ifndef __DC_MOTOR_COMMON_H
#define __DC_MOTOR_COMMON_H
#include <stdint.h>

#ifndef DC_MOTOR_MAX_RPM_SPEED
//! Max RPM for a DC motor
#define DC_MOTOR_MAX_RPM_SPEED 200
#endif

#ifndef DC_ENC_SIGNALS_PER_ROUND
//! Number of signals generated by the encoder for each round
#define DC_ENC_SIGNALS_PER_ROUND 1130
#endif

//! Real RPM speed sampling interval in milliseconds
#define DC_SAMPLING_INTERVAL 100

//! Handle DC motor number
#define DC_MOTOR_NUM 4

//! Predefined selector value with all motors selected
#define DC_MOTOR_SEL_ALL (0xFF << (8-DC_MOTOR_NUM) >> (8-DC_MOTOR_NUM))

//! Type to properly store a rounds per minute value
typedef int16_t dc_rpm_t;

#endif  // __DC_MOTOR_COMMON_H
